# Generated by Django 4.1.6 on 2023-03-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_name', models.CharField(max_length=100)),
                ('shipping_type', models.CharField(max_length=100)),
                ('container_no', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('heigh', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('goodsType', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.CharField(blank=True, max_length=100)),
                ('pickup_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('arrival_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shipment_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_company', models.CharField(max_length=100)),
                ('receiver_country', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_address_2', models.CharField(max_length=100)),
                ('receiver_address_3', models.CharField(max_length=100)),
                ('postal_code', models.BigIntegerField(null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('country_code', models.BigIntegerField(null=True)),
                ('taxt_no', models.IntegerField(null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingto', to='authentication.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['receiver_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_company', models.CharField(max_length=100)),
                ('sender_country', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_address_2', models.CharField(max_length=100)),
                ('sender_address_3', models.CharField(max_length=100)),
                ('postal_code', models.BigIntegerField(null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('country_code', models.BigIntegerField(null=True)),
                ('taxt_no', models.BigIntegerField(null=True)),
                ('vat_no', models.IntegerField(null=True)),
                ('shippingto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingfrom', to='authentication.shippingto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingfrom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sender_name'],
            },
        ),
    ]
