# Generated by Django 4.1.6 on 2023-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tracking_no',
            field=models.CharField(default='226268985793', max_length=12, unique=True),
        ),
    ]
